### ISSUE TITLE
api版本提示网路错误

### ISSUE THREAD

**Issue by Carlos6668** [w2r/hostloc2tg#4]
nohup: ignoring input
网络错误，请稍后重试
网络错误，请稍后重试

是否脚本改了

**Comment by elunez** [comment]
> nohup: ignoring input 网络错误，请稍后重试 网络错误，请稍后重试
> 
> 是否脚本改了

同样的问题出现在美国服务器上面，香港服务器不会出现网络错误问题，你解决了吗
